# Generated by Django 5.1.3 on 2025-02-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='미지정', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='school_email',
            field=models.EmailField(default='example@tukorea.ac.kr', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='2024000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
