# Generated by Django 5.1.3 on 2025-02-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('registration', '회원가입'), ('password_reset', '비밀번호 변경')], default='registration', max_length=20),
        ),
    ]
