# Generated by Django 5.1.3 on 2025-02-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_image_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('FOR_SALE', '판매 중'), ('IN_PROGRESS', '거래 중'), ('COMPLETED', '거래 완료')], default='FOR_SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='major',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
